---
author: Ernest Orlowski
engine: julia
format: html
title: "Gaussian Process Regression"
---

The method below is described in the dissertation "Stochastic differential
equation methods for spatio-temporal Gaussian process regression." by Arno Solin
and "Sequential Inference for Latent Temporal Gaussian Process Models" by Jouni
Hartikainen. The method is as follows:

Suppose a function $f(x)$ follows a zero-mean Gaussian Process

$$
f(x) \backsim \mathbfit{GP}(0, \mathbfit{k}(x, x\prime))
$$

<!-- below is a quick python script to test which TeX font is being used. -->

```{python .hidden}
%reload_ext autoreload
%autoreload 2

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "last_expr_or_assign"

import pandas as pd
# pd.options.mode.copy_on_write = True # standard on pd >3.0
import matplotlib as mpl
import matplotlib.pyplot as plt
# %matplotlib inline # no really needed inside vscode
mpl.use("agg")

# `constrained_layout` helps avoid overlapping elements
# Refer to https://matplotlib.org/stable/tutorials/intermediate/constrainedlayout_guide.html
plt.rcParams['figure.constrained_layout.use'] = True

# helper func to create a grid layout for subplots
def make_grid(label = None, ncols = None, nrows = None, placeholder = "."):
    """
    Create a grid layout suitable for matplotlibs subplot_mosaic.
    If `labels` is None, auto-generat labels like `A1`, `A2`, ..., `B1`, `B2`, ...

    Args:
        labels (list of str or None): Subplot labels.. If None, generate from ncols and nrows.
        ncols (int or None): Number of cols in the grid (required).
        nrows (int or None): Number of rows (required if labels is None).
        placeholder (str): Placeholder for empty cells in the grid.

    Returns:
        list of list of str: A 2D list representing the grid layout.
    """
    import string
    import itertools

    if ncols is None or ncols <= 0:
        raise ValueError("ncols must be a positive integer.")

    if labels is None:
            if nrows is None:
                raise ValueError("If labels is None, nrows must be specified.")

            def _excel_style_name():
                for size in itertools.count(1):
                    for chars in itertools.product(string.ascii_uppercase, repeat=size):
                        yield "".join(chars)

            row_names = itertools.islice(_excel_style_name(), nrows)
            labels = [f"{row}{col + 1}" for row in row_names for col in range(ncols)]

        grid = [labels[i:i + ncols] for i in range(0, len(labels), ncols)]

        if len(grid[-1]) < ncols:
            grid[-1].extend([placeholder] * (ncols - len(grid[-1])))

        return grid
```

```{python}

fig, ax = plt.subplots()

ax.plot([1, 2, 3], label=r"$\sqrt{x^2}$")
ax.legend()

ax.set_xlabel(r"$\Delta_i^j$", fontdict={"size": 20})
ax.set_ylabel(r"$\Delta_{i+1}^j$", fontdict={"size": 20})
ax.set_title(
    r"$\Delta_i^j \hspace{0.4} \mathrm{versus} \hspace{0.4}$ "
    r"$\Delta_{i+1}^j$",
    fontdict={"size": 20},
)

tex = r"$\mathcal{R}\prod_{i = \alpha_{i + 1}}^\infty a_i\sin(2 \pi f x_i)$"
ax.text(1, 1.6, tex, fontdict={"size": 20}, va="bottom")

fig.tight_layout()
plt.show()
```

<!-- NOTE: More complex example -->

```{python}

import numpy as np

fig, ax = plt.subplots()

N = 500
delta = 0.6
X = np.linspace(-1, 1, N)

ax.plot(
    X,
    (1 - np.tanh(4 * X / delta)) / 2,  # phase field tanh profiles
    X,
    (1.4 + np.tanh(4 * X / delta)) / 4,
    "C2",  # composition profile
    X,
    X < 0,
    "k--",
)
# legend
ax.legend(
    ("phase field", "level set", "sharp interface"),
    shadow=True,
    loc=(0.01, 0.48),
    handlelength=1.5,
    fontsize=16,
)

# arrow
ax.annotate(
    "",
    xy=(-delta / 2.0, 0.1),
    xytext=(delta / 2.0, 0.1),
    arrowprops={"arrowstyle": "<->", "connectionstyle": "arc3"},
)
ax.text(
    0,
    0.1,
    r"$\delta$",
    color="black",
    fontdict={"size": 24},
    horizontalalignment="center",
    verticalalignment="center",
    bbox={"boxstyle": "round", "fc": "white", "ec": "black", "pad": 0.2},
)

# text in labels
ax.set_xticks([-1, 0, 1])
ax.set_xticklabels(["$-1$", r"$\pm 0$", "$+1$"], color="k", size=20)

# Left Y-axis labels, combine math mode and text mode
ax.set_ylabel(r"$\mathbf{phase field} \phi$", color="C0", fontdict={"size": 20})
ax.set_yticks([0, 0.5, 1])
ax.set_yticklabels(
    [r"$\mathbf{0}$", r"$\mathbf{.5}$", r"$\mathbf{1}$"],
    color="k",
    fontdict={"size": 20},
)

# right y-axis labels
ax.text(
    1.02,
    0.5,
    r"$\mathbf{level set} \phi$",
    color="C2",
    fontsize=20,
    rotation=90,
    horizontalalignment="left",
    verticalalignment="center",
    clip_on=False,
    transform=ax.transAxes,
)

# use multiline environment inside a `text`
# level set equations
# from IPython.display import Latex, Markdown, Math, display

eq1 = (
    "$\\begin{equation}$"
    "$\nabla\phi| &=& 1,\\$"
    "$\frac{\partial \phi}{\partial t} + U|\nabla \phi| &=& 0$"
    "$\end{equation*}$"
)

# eq1 = r"""
# \begin{equation}
#    \nabla\phi| &=& 1,\\
#    \frac{\partial \phi}{\partial t} + U|\nabla \phi| &=& 0
# end{equation*}
# """

ax.text(
    1,
    0.9,
    eq1,
    color="C2",
    fontdict={"size": 18},
    horizontalalignment="right",
    verticalalignment="top",
)

# phase field equations
eq2 = (
    r"$\begin{equation}$"
    r"$\mathcal{F} &=& \int f\left( \phi, c \right) dV, \\$ "
    r"$\frac{ \partial \phi }{ \partial t } &=& -M_{ \phi }$ "
    r"$\frac{ \delta \mathcal{F} }{ \delta \phi }$"
    r"$\end{equation*}$",
)

# eq2 = r"""
#     \begin{equation}
#         \mathcal{F} &=& \int f\left( \phi, c \right) dV, \\,
#         \frac{ \partial \phi }{ \partial t } &=& -M_{ \phi }
#         \frac{ \delta \mathcal{F} }{ \delta \phi }
#     \end{equation*}
# """

ax.text(0.18, 0.18, eq2, color="C0", fontdict={"size": 16})

ax.text(-1, 0.30, r"gamma: $\gamma$", color="r", fontdict={"size": 20})
ax.text(-1, 0.18, r"Omega: $\Omega$", color="b", fontdict={"size": 20})

plt.show()
```

When the dimensionality of $x$ is 1, we consider $f(x)$ as a stochastic process
over time, i.e. $f(t)$. For certain classes of covariance functions, $f(t)$ is
a solution to an $m$-th order linear stochastic differential equation (SDE).

$$
a_0 f(t) + a_1 \frac{\mathcal{d}f(t)}{\mathcal{d}t} + \dots + a_{m}
\frac{\mathcal{d^m}f(t)}{\mathcal{d}t^m} = \omega (t)
$$

where $\omega (t)$ is a zero-mean white noise process with spectral density
$Q_c$. If we define a vector-valued function $f(t) = (f(t), d/dt f(t)), \dots,
d^{m-1}/dt^{m-1}f(t))$, then we can rewrite the above SDE under the companion form:

$$
\frac{\mathcal{d}f(t)}{\mathcal{d}t} = \mathbf{F}f(t) + \mathbf{L}\omega(t) \label{1}
$$

Where $\mathbf{F}$ and $\mathbf{L}$ are defined based on the choice of
covariance functions. From $\label{1}$, we have the following state-space model:

$$
\begin{aligned}
    \mathbf{f}_k = \mathbf{A}_{k-1} \,\mathbf{f}_{k-1} + \mathbf{q}_{k-1}, \quad \mathbf{q}_{k-1} \sim \mathcal{N}(\mathbf{0}, \mathbf{Q}_{k-1}) \quad(2a) \\
    y_k = \mathbf{H} \, \mathbf{f}(t_k) + \epsilon_k , \quad \epsilon_k \sim \mathcal{N}(0, \sigma^2_{noise}) \quad(2b)
\end{aligned}
$$
