[project]
name = "setosa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "eo1989", email = "7108365+eo1989@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "jsonschema>=4.26.0",
    "kitcat>=1.2.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pip>=26.0.1",
    "pyyaml>=6.0.3",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "setuptools>=82.0.0",
    "wheel>=0.46.3",
]

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pytest>=9.0.2",
]
