---
engine: julia
author: "Ernest Orlowski"
format:
  html:
    code-fold: true
    page-layout: full
    grid:
        margin-width: 450px
        body-width: 600px
---

# Inference Concepts

To make a statistical inference involves *data*, a *model*, and *analysis*. The data is assumed to be compromised of random samples from the model. The goal of the analysis is then to make informed statements about population parameters of the model based on the data. Such statementstypically take one of the following forms:

> *Point estimation* - Determination of a single value (or vector of values) representing a best estimate of the parameter(s). In this case, the notion of "best" can be defined in different ways.
> *Confidence intervals* - Determination of a range of values where the parameter lies. Under the model and the statistical process used, it is garaunteed that the parameter lies within this range with a pre-specified probability.
> *Hypothesis tests* - The process of determining if the parameter lies in a given region, in the complement of that region, or fails to take on a specific value. Such tests often represent a scientific hypothesis in a very natural way.

Most point estimation, confidence intervals, and hypothesis tests here are elementary. See `chapter 6` to confidence intervals in detail, and `chapter 7` to hypothesis tests in detail.

As a refresher, when carrying out frequentist statistical inference, its assumed there is some underlying distribution $F(x;\theta)$ from which our samples are taken, where $\theta$ is a scalar, or vector-valued, unknown parameter we want to know. It's also assumed that each observation is statistically independent and identically distributed as the rest, meaning the observations are taken as *i.i.d. random variables*. This is the `random sample` in mathematical statistics. Random variables of the observations are denoted by $X_1, ..., X_n$, and their respective values by $x_1, ..., x_n$. Typically, *statistics* are computed from the `random sample`, like the *sample mean* and *sample variance*. However, ee can model these *statistics* as random variables themselves.
$$
\bar{X} = \frac{1}{n} \Sigma^{n}_{i=1}X_{i}\text{, } \enspace \text{ and } S^{2} = \frac{1}{n - 1}  \Sigma^{n}_{i=1}(X_{i} - \bar{X})^{2}
$$

Note: that for $S^2$, the denominator is $n - 1$ (as opposed to $n$ as you might expect). This makes $S^2$ an ***unbiased estimator***.

The phrase *statistic* implies a quantity calculated based on the sample. When working with data, the sample mean and variance are nothing but numbers computed from our sample observations. That being said, in the inference paradigm, random variables are associated to these values, since they themselves are functions of the random sample.

A great way to see the fact that $\bar{X}$ and $S^2$ are `random variables`, is to assume we have sampled data from an exponential distribution with $\lambda = 4.5^{-1}$ (a mean of 4.5 and a variance of 20.25). If $n = 10$ observations, then the sample mean, and variance, are random variables.


```{julia}
#| code-line-numbers: true
#| width: 1200
using Distributions, Plots;
pyplot();

μ, σ = 10, 4
n, N = 10, 10^6

s_μ = Array{Float64}(undef, N)
s_var = Array{Float64}(undef, N)
t_stats = Array{Float64}(undef, N)

for i in 1:N
    data = rand(Normal(μ, σ), n)
    sample_μ = mean(data)
    sample_vars = var(data)
    s_μ[i] = sample_μ
    s_var[i] = sample_vars
    t_stats[i] = (sample_μ - μ) / (sqrt(sample_vars / n))
end

xRange_μ = 5:0.1:15
xRange_var = 0:0.1:60
xRange_tstat = -5:0.1:5

p1 = stephist(s_μ, bins=50, c=:blue, normed=true, legend=false)
p1 = plot!(xRange_μ, pdf.(Normal(μ, σ / sqrt(n)), xRange_μ), c=:red, xlims=(5, 15), ylims=(0, 0.35), xlabel="Sample μ", ylabel="Density")

p2 = stephist(s_var, bins=50, c=:blue, normed=true, label="Simulated")
p2 = plot!(xRange_var, (n - 1) / σ^2 * pdf.(Chisq(n - 1), xRange_var * (n - 1) / σ^2), c=:red, label="Analytic", xlims=(0, 60), ylims=(0, 0.06), xlabel="Sample Variance", ylabel="Density")

p3 = stephist(t_stats, bins=100, c=:blue, normed=true, legend=false)
p3 = plot!(xRange_tstat, pdf.(TDist(n - 1), xRange_tstat), c=:red, xlims=(-5, 5), ylims=(0, 0.4), xlabel="t-statistic", ylabel="Density")

plot(p1, p2, p3, layout=(1, 3), size=(1200, 400))

```
